// Single-file build for INNSMOUTH 2000.
//
// Inlines every src module into one self-contained dist/innsmouth2000.html that runs from a
// double-clicked file:// with zero dependencies and no dev server (CLAUDE.md hard rule 6). We
// have no bundler dependency, so this is a small, deterministic inliner: concatenate the modules
// in dependency order, strip our own import/export syntax (leaving the declarations), wrap the
// whole thing in an IIFE, and boot it against the page canvas.

import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Dependency order: each module may only reference symbols from earlier modules.
//
// Two rules this list enforces by hand, both of which have silently produced a blank build:
//   1. EVERY module under src/ must be listed. One left out is dropped from the bundle, the build
//      still reports success, `node --test` stays green (it imports the real modules), and only
//      the built page dies on its first missing symbol.
//   2. Because every module lands in ONE shared scope, top-level identifiers must be unique
//      across all of src/. Two modules with a private `const NB` is a fatal redeclaration.
// test/build.test.js now holds both, so neither can reach dist again.
export const MODULES = [
  'src/rng.js',
  'src/geometry.js',
  'src/palette.js',
  'src/music.js', // a leaf (no imports of ours); ui.js reads its volume constants
  'src/mapgen.js',
  'src/camera.js',
  'src/aquifer.js', // the subsurface substrate (M-b); tools.js reads it for the sealing works
  'src/tools.js',
  'src/power.js',
  'src/water.js',
  'src/gods.js',
  'src/deep.js', // the Deep Ones layer (M-b); disasters.js pushes presence on a Flood Tide
  'src/disasters.js',
  'src/sim.js',
  'src/scenarios.js',
  'src/ambient.js',
  'src/render.js',
  'src/ui.js',
  'src/overlays.js',
  'src/strips.js',
  'src/save.js',
  'src/advisor.js',
  'src/main.js',
];

// Strip ES module syntax so the concatenation runs as one plain script.
export function stripModuleSyntax(code) {
  // Drop import statements first, including multi-line `import { ... } from '...';` blocks.
  const noImports = code.replace(/^import\s[^;]*?from\s+['"][^'"]+['"];?\s*$/gm, '');
  return noImports
    .split('\n')
    .filter((line) => !/^\s*export\s*\{[^}]*\}\s*;?\s*$/.test(line)) // drop re-export lines
    .map((line) => line.replace(/^(\s*)export\s+(const|function|class|let|var|async)\s/, '$1$2 '))
    .join('\n');
}

const banner = '// INNSMOUTH 2000 — single-file build. Generated by scripts/build.js; do not edit by hand.';

// The concatenated script, exactly as the built page carries it. Exported and side-effect free so
// test/build.test.js can parse-check the real bundle without running a build or trusting a stale
// dist/ on disk.
export function buildBundle() {
  return MODULES
    .map((rel) => `\n// ===== ${rel} =====\n${stripModuleSyntax(readFileSync(join(ROOT, rel), 'utf8'))}`)
    .join('\n');
}

// Everything below writes to disk, so it only runs when this file is invoked as the build script.
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (!isMain) { /* imported for its pure helpers; write nothing */ } else {

const bundle = buildBundle();

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>INNSMOUTH 2000</title>
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="INNSMOUTH 2000" />
  <meta property="og:title" content="INNSMOUTH 2000" />
  <meta property="og:description" content="A Lovecraftian take on the classic 1993 city-builder: zone a rotting coastal town and appease five gods whose wrath is the disasters menu. Playable in the browser." />
  <meta property="og:url" content="https://i2-preview.pages.dev/" />
  <meta property="og:image" content="https://i2-preview.pages.dev/og.png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="INNSMOUTH 2000" />
  <meta name="twitter:description" content="A Lovecraftian take on the classic 1993 city-builder. Playable in the browser." />
  <meta name="twitter:image" content="https://i2-preview.pages.dev/og.png" />
  <style>
    html, body { margin: 0; height: 100%; background: #20242a; overflow: hidden; }
    #screen { display: block; width: 100vw; height: 100vh; image-rendering: pixelated; cursor: crosshair; }
  </style>
</head>
<body>
  <canvas id="screen"></canvas>
  <script>
${banner}
(function () {
'use strict';
${bundle}

boot(document.getElementById('screen'));
})();
  </script>
</body>
</html>
`;

mkdirSync(join(ROOT, 'dist'), { recursive: true });
const out = join(ROOT, 'dist', 'innsmouth2000.html');
writeFileSync(out, html);
const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
console.log(`built ${out} (${kb} KB, ${MODULES.length} modules inlined)`);

// The music package (M9.6, operator-directed): the single-file build stays lean and does NOT
// inline the tracks (graceful absence — a bare double-clicked innsmouth2000.html runs silent with
// no assets/music/ beside it). For a distribution that plays music, zip the html together with
// assets/music/ so extracting keeps them side by side, which is the relative path music.js reads
// from. Skipped quietly if the operator hasn't supplied any tracks yet.
const musicDir = join(ROOT, 'assets', 'music');
if (existsSync(musicDir)) {
  const stage = join(ROOT, 'dist', '.zipstage');
  rmSync(stage, { recursive: true, force: true });
  mkdirSync(stage, { recursive: true });
  cpSync(out, join(stage, 'innsmouth2000.html'));
  cpSync(musicDir, join(stage, 'assets', 'music'), { recursive: true });
  const zipOut = join(ROOT, 'dist', 'innsmouth2000-with-music.zip');
  rmSync(zipOut, { force: true });
  execFileSync('zip', ['-r', '-X', '-q', zipOut, 'innsmouth2000.html', 'assets'], { cwd: stage });
  rmSync(stage, { recursive: true, force: true });
  const zipKb = (statSync(zipOut).size / 1024).toFixed(0);
  console.log(`built ${zipOut} (${zipKb} KB: the html + assets/music/, side by side)`);
}

} // end of the run-as-script block
