// provenance.js — THE CREDITS, as the player can read them (M8's ship shell).
//
// ATTRIBUTION.md has shipped inside dist/index.html since M1, but only as an HTML comment: present
// in the artifact, and invisible to anybody actually playing the game. The cast pack carries CC BY,
// which is a condition of use and not a courtesy, so the credit has to be somewhere a person can
// see it without opening the file in a text editor. This module is that surface.
//
// IT IS ALSO A DRIFT GUARD. A standing test asserts that every load-bearing fact below also appears
// in ATTRIBUTION.md, so the in-game credits and the shipped licence file cannot say different
// things. The failure this prevents is the ordinary one: an asset changes, one of the two records
// is updated, and the game quietly starts crediting the wrong person.

export const PROVENANCE_TITLE = 'PROVENANCE';

// Each line is [style, text]. 'head' is a printed heading, 'body' is an entry, '' is a spacer.
// Body lines are held to 69 characters, which is what the 11px body face actually fits in the
// sheet's 456px column. That number was MEASURED against the real font in the real artifact, not
// estimated: the first version of this file guessed 84, its guard test passed, and the credits
// ran off the right edge of the paper into the ledger beside it. A licence condition the player
// cannot read is the one place in this game where legibility is also a legal matter.
//
// The renderer wraps these as well, so an overlong line degrades to two lines rather than to text
// off the edge of the sheet. The limit keeps the section heights predictable; the wrap is the net.
export const PROVENANCE = Object.freeze([
  ['head', 'THE FACILITY'],
  ['body', 'Code-drawn at native resolution. No image was generated by a model.'],
  ['', ''],
  ['head', 'THE CAST'],
  ['body', 'NPC Pack - Human Empires, by Willibab / Monsteretrope. CC BY 4.0.'],
  ['body', "Recoloured into this game's palette; the originals are preserved."],
  ['', ''],
  ['head', 'THE TYPE'],
  ['body', 'Not Jam Font Pack, by Not Jam. Licensed CC0 1.0.'],
  ['body', 'Slab Serif 11 for the printed form; Serif 11 for the entries.'],
  ['', ''],
  ['head', 'THE SCORE'],
  ['body', 'Abel Aeolian. Code-composed WebAudio; no audio file ships.'],
  ['', ''],
  ['head', 'STANDING'],
  ['body', 'No LLM-image-generated art appears in this game, in any form.'],
]);

// The measured column width, in characters of the 11px body face. Exported so the guard test
// asserts the real figure rather than restating a guess.
export const CREDIT_LINE_MAX_CHARS = 69;

// The facts the drift guard checks against ATTRIBUTION.md. Each must appear in both.
export const PROVENANCE_FACTS = Object.freeze([
  'NPC Pack',
  'Willibab',
  'CC BY 4.0',
  'Not Jam',
  'CC0',
  'Abel Aeolian',
]);
