#!/usr/bin/env python3
"""Bake Atkinson Hyperlegible Regular into a pure JS alpha glyph atlas."""

from __future__ import annotations

import base64
import json
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
TTF = ROOT / "vendor/fonts/AtkinsonHyperlegible-Regular.ttf"
OUT = ROOT / "src/gfx/bodyFontData.js"
SIZE = 11
CHARS = "".join(chr(i) for i in range(32, 127))

b64 = base64.b64encode(TTF.read_bytes()).decode("ascii")
html = f"""<!DOCTYPE html><html><head><style>
@font-face {{
  font-family: 'BodyBake';
  src: url(data:font/ttf;base64,{b64}) format('truetype');
  font-weight: 400;
  font-style: normal;
}}
body {{ margin: 0; background: #000; }}
</style></head><body>
<canvas id="c" width="64" height="64"></canvas>
<script>
window.__bake = async function(chars, size) {{
  await document.fonts.load(size + 'px BodyBake');
  await document.fonts.ready;
  const canvas = document.getElementById('c');
  const ctx = canvas.getContext('2d', {{ willReadFrequently: true }});
  ctx.font = size + 'px BodyBake';
  ctx.textBaseline = 'alphabetic';
  const metrics = ctx.measureText('Hg');
  const ascent = Math.ceil(metrics.actualBoundingBoxAscent || size * 0.8);
  const descent = Math.ceil(metrics.actualBoundingBoxDescent || size * 0.2);
  const lineHeight = ascent + descent + 2;
  const glyphs = {{}};
  for (const ch of chars) {{
    const adv = Math.max(1, Math.ceil(ctx.measureText(ch).width));
    const pad = 2;
    const w = adv + pad * 2;
    const h = lineHeight + pad;
    canvas.width = w;
    canvas.height = h;
    ctx.clearRect(0, 0, w, h);
    ctx.font = size + 'px BodyBake';
    ctx.textBaseline = 'alphabetic';
    ctx.fillStyle = '#fff';
    const baseline = ascent + 1;
    ctx.fillText(ch, pad, baseline);
    const img = ctx.getImageData(0, 0, w, h).data;
    let minX = w, minY = h, maxX = -1, maxY = -1;
    for (let y = 0; y < h; y++) {{
      for (let x = 0; x < w; x++) {{
        const a = img[(y * w + x) * 4 + 3];
        if (a < 40) continue;
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }}
    }}
    if (maxX < 0) {{
      glyphs[ch] = {{ w: Math.max(3, Math.round(adv * 0.55)), h: 0, ox: 0, oy: 0, rows: [] }};
      continue;
    }}
    const gw = maxX - minX + 1;
    const gh = maxY - minY + 1;
    const rows = [];
    for (let y = minY; y <= maxY; y++) {{
      let row = '';
      for (let x = minX; x <= maxX; x++) {{
        const a = img[(y * w + x) * 4 + 3];
        row += a >= 40 ? '#' : '.';
      }}
      rows.push(row);
    }}
    glyphs[ch] = {{
      w: Math.max(gw, Math.round(adv)),
      h: gh,
      ox: minX - pad,
      oy: minY - 1,
      rows,
    }};
  }}
  return {{ size, ascent, descent, lineHeight, spaceAdvance: glyphs[' '].w, glyphs }};
}};
</script></body></html>
"""

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.set_content(html, wait_until="load")
    data = page.evaluate(
        """async ({ chars, size }) => window.__bake(chars, size)""",
        {"chars": CHARS, "size": SIZE},
    )
    browser.close()

meta = {
    "family": "Atkinson Hyperlegible",
    "size": data["size"],
    "ascent": data["ascent"],
    "descent": data["descent"],
    "lineHeight": data["lineHeight"],
    "spaceAdvance": data["spaceAdvance"],
}

header = """// AUTO-GENERATED by scripts/bake-body-font.py — do not hand-edit.
// Source: vendor/fonts/AtkinsonHyperlegible-Regular.ttf (SIL Open Font License 1.1).
// License text: vendor/fonts/OFL-AtkinsonHyperlegible.txt
"""

out = (
    header
    + f"export const BODY_FONT_META = {json.dumps(meta, indent=2)};\n\n"
    + f"export const BODY_GLYPHS = {json.dumps(data['glyphs'], indent=2)};\n"
)
OUT.write_text(out)
print(
    f"wrote {OUT.relative_to(ROOT)} "
    f"({OUT.stat().st_size / 1024:.1f} KB, {len(data['glyphs'])} glyphs)"
)
print(f"lineHeight={data['lineHeight']} ascent={data['ascent']}")
